// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package src

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc(in *jlexer.Lexer, out *QueryMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "identity":
			if in.IsNull() {
				in.Skip()
				out.Identity = nil
			} else {
				if out.Identity == nil {
					out.Identity = new(QueryIdentity)
				}
				(*out.Identity).UnmarshalTinyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc(out *jwriter.Writer, in QueryMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"identity\":"
		out.RawString(prefix[1:])
		if in.Identity == nil {
			out.RawString("null")
		} else {
			(*in.Identity).MarshalTinyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v QueryMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v QueryMsg) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *QueryMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *QueryMsg) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc(l, v)
}
func tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc1(in *jlexer.Lexer, out *QueryIdentity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc1(out *jwriter.Writer, in QueryIdentity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v QueryIdentity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v QueryIdentity) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *QueryIdentity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc1(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *QueryIdentity) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc1(l, v)
}
func tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc2(in *jlexer.Lexer, out *MsgUpdateCity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "city":
			out.City = string(in.String())
		case "postal_code":
			out.PostalCode = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc2(out *jwriter.Writer, in MsgUpdateCity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix[1:])
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"postal_code\":"
		out.RawString(prefix)
		out.Int32(int32(in.PostalCode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MsgUpdateCity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MsgUpdateCity) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MsgUpdateCity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc2(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MsgUpdateCity) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc2(l, v)
}
func tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc3(in *jlexer.Lexer, out *MsgDelete) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc3(out *jwriter.Writer, in MsgDelete) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MsgDelete) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MsgDelete) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MsgDelete) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc3(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MsgDelete) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc3(l, v)
}
func tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc4(in *jlexer.Lexer, out *MsgCreateIdentity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "surname":
			out.Surname = string(in.String())
		case "city":
			out.City = string(in.String())
		case "postal_code":
			out.PostalCode = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc4(out *jwriter.Writer, in MsgCreateIdentity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"surname\":"
		out.RawString(prefix)
		out.String(string(in.Surname))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"postal_code\":"
		out.RawString(prefix)
		out.Int32(int32(in.PostalCode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MsgCreateIdentity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MsgCreateIdentity) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MsgCreateIdentity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc4(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MsgCreateIdentity) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc4(l, v)
}
func tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc5(in *jlexer.Lexer, out *ExecuteMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "create_identity":
			if in.IsNull() {
				in.Skip()
				out.CreateIdentity = nil
			} else {
				if out.CreateIdentity == nil {
					out.CreateIdentity = new(MsgCreateIdentity)
				}
				(*out.CreateIdentity).UnmarshalTinyJSON(in)
			}
		case "update_city":
			if in.IsNull() {
				in.Skip()
				out.UpdateCity = nil
			} else {
				if out.UpdateCity == nil {
					out.UpdateCity = new(MsgUpdateCity)
				}
				(*out.UpdateCity).UnmarshalTinyJSON(in)
			}
		case "delete_identity":
			if in.IsNull() {
				in.Skip()
				out.DeleteIdentity = nil
			} else {
				if out.DeleteIdentity == nil {
					out.DeleteIdentity = new(MsgDelete)
				}
				(*out.DeleteIdentity).UnmarshalTinyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc5(out *jwriter.Writer, in ExecuteMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"create_identity\":"
		out.RawString(prefix[1:])
		if in.CreateIdentity == nil {
			out.RawString("null")
		} else {
			(*in.CreateIdentity).MarshalTinyJSON(out)
		}
	}
	{
		const prefix string = ",\"update_city\":"
		out.RawString(prefix)
		if in.UpdateCity == nil {
			out.RawString("null")
		} else {
			(*in.UpdateCity).MarshalTinyJSON(out)
		}
	}
	{
		const prefix string = ",\"delete_identity\":"
		out.RawString(prefix)
		if in.DeleteIdentity == nil {
			out.RawString("null")
		} else {
			(*in.DeleteIdentity).MarshalTinyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExecuteMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ExecuteMsg) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4a7bbd12EncodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExecuteMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc5(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ExecuteMsg) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4a7bbd12DecodeGithubComCosmwasmCosmwasmGoExampleIdentitySrc5(l, v)
}
