// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonC6ca534cDecodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes(in *jlexer.Lexer, out *MsgIBC) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "vote":
			if in.IsNull() {
				in.Skip()
				out.Vote = nil
			} else {
				if out.Vote == nil {
					out.Vote = new(IBCVoteRequest)
				}
				(*out.Vote).UnmarshalTinyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonC6ca534cEncodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes(out *jwriter.Writer, in MsgIBC) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Vote != nil {
		const prefix string = ",\"vote\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Vote).MarshalTinyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MsgIBC) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjsonC6ca534cEncodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MsgIBC) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonC6ca534cEncodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MsgIBC) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjsonC6ca534cDecodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MsgIBC) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonC6ca534cDecodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes(l, v)
}
func tinyjsonC6ca534cDecodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes1(in *jlexer.Lexer, out *IBCVoteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			out.From = string(in.String())
		case "id":
			out.ID = uint64(in.Uint64())
		case "option":
			out.Option = string(in.String())
		case "vote":
			out.Vote = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonC6ca534cEncodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes1(out *jwriter.Writer, in IBCVoteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"option\":"
		out.RawString(prefix)
		out.String(string(in.Option))
	}
	{
		const prefix string = ",\"vote\":"
		out.RawString(prefix)
		out.String(string(in.Vote))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IBCVoteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjsonC6ca534cEncodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v IBCVoteRequest) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonC6ca534cEncodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IBCVoteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjsonC6ca534cDecodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes1(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *IBCVoteRequest) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonC6ca534cDecodeGithubComCosmWasmCosmwasmGoExampleVoterSrcTypes1(l, v)
}
