# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_contracts:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Build Hackatom contract
          command: make hackatom
      - run:
          name: Build Queue contract
          command: make queue
      - run:
          name: Collect artifacts
          command: |
            mkdir artifacts
            cp ./example/hackatom/hackatom.wasm artifacts
            cp ./example/queue/queue.wasm artifacts
      - run:
          name: Create checksums
          working_directory: artifacts
          command: sha256sum * > checksums.txt && cat checksums.txt
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - hackatom.wasm
            - queue.wasm

  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/builds
      - run:
          name: check
          command: ls -l /tmp/builds
      - restore_cache:
          keys:
            - go-mod-v5-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v5-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: Copy build contracts
          command: |
            cp /tmp/builds/hackatom.wasm ./example/hackatom/hackatom.wasm
            cp /tmp/builds/queue.wasm ./example/queue/queue.wasm
      - run:
          name: Hackatom integration tests
          command: |
            cd example/hackatom
            go test -v -count=1 ./integration
      - run:
          name: Queue contract integration tests
          command: |
            cd example/queue
            go test -v -count=1 ./integration
      - run:
          name: Try gotestsum
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml ./std
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_contracts
      - test:
          requires:
            - build_contracts