// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson631e4b7dDecodeGithubComCosmwasmCosmwasmGoStdTypes(in *jlexer.Lexer, out *ContractError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			out.Err = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson631e4b7dEncodeGithubComCosmwasmCosmwasmGoStdTypes(out *jwriter.Writer, in ContractError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		out.String(string(in.Err))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ContractError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson631e4b7dEncodeGithubComCosmwasmCosmwasmGoStdTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ContractError) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson631e4b7dEncodeGithubComCosmwasmCosmwasmGoStdTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContractError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson631e4b7dDecodeGithubComCosmwasmCosmwasmGoStdTypes(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ContractError) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson631e4b7dDecodeGithubComCosmwasmCosmwasmGoStdTypes(l, v)
}
