// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package src

import (
	easyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBd887cf1DecodeGithubComCosmwasmCosmwasmGoExampleHackatomSrc(in *jlexer.Lexer, out *State) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "VERIFIER":
			out.Verifier = string(in.String())
		case "BENEFICIARY":
			out.Beneficiary = string(in.String())
		case "FUNDER":
			out.Funder = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeGithubComCosmwasmCosmwasmGoExampleHackatomSrc(out *jwriter.Writer, in State) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"VERIFIER\":"
		out.RawString(prefix[1:])
		out.String(string(in.Verifier))
	}
	{
		const prefix string = ",\"BENEFICIARY\":"
		out.RawString(prefix)
		out.String(string(in.Beneficiary))
	}
	{
		const prefix string = ",\"FUNDER\":"
		out.RawString(prefix)
		out.String(string(in.Funder))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v State) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeGithubComCosmwasmCosmwasmGoExampleHackatomSrc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v State) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeGithubComCosmwasmCosmwasmGoExampleHackatomSrc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *State) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeGithubComCosmwasmCosmwasmGoExampleHackatomSrc(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *State) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeGithubComCosmwasmCosmwasmGoExampleHackatomSrc(l, v)
}
