// +build  cosmwasm

// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package std

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (ContractError) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ContractError) UnmarshalJSON([]byte) error        { return nil }
func (ContractError) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ContractError) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ContractError *ContractError
